weights: ''
cfg: models/yolov5sn.yaml
data: /cluster/home/it_stu4/Data/RM-keypoint-4-9-Oplus/armor.yaml
hyp: data/hyps/RM.armor.yaml
epochs: 500
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: true
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 16
project: runs/train
name: 8-3-test
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: 100
local_rank: -1
negative_path:
- /cluster/home/it_stu4/Data/COCO/unlabeled2017/
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/8-3-test
